name = "amazonmusic-api"
main = "dist/index.js"
compatibility_date = "2024-01-01"
account_id = "cd4ab75cca150f63177325a6bb1c355f"

[build]
command = "npm run build"

# Development settings
[env.development]
workers_dev = true

# Production settings
[env.production]
workers_dev = false
routes = []
